schemes:
  afterglow: &afterglow
  # Default colors
    primary:
      background: '#2c2c2c'
      foreground: '#d6d6d6'

      dim_foreground:    '#dbdbdb'
      bright_foreground: '#d9d9d9'
      dim_background:    '#202020' # not sure
      bright_background: '#3a3a3a' # not sure

    # cursor colors
    cursor:
      text:   '#2c2c2c'
      cursor: '#d9d9d9'

    # Vi mode cursor colors
    # vi_mode_cursor:
    #   text: CellBackground
    #   cursor: CellForeground

    # Search colors
    # search:
    #   matches:
    #     foreground: '#000000'
    #     background: '#ffffff'

    #   focused_match:
    #     foreground: '#ffffff'
    #     background: '#000000'

    # hints:
    #   start:
    #     foreground: '#1d1f21'
    #     background: '#e9ff5e'

    #   end:
    #     foreground: '#e9ff5e'
    #     background: '#1d1f21'

    # line_indicatro:
    #   foreground: None
    #   background: None

    #footer_bar:
    #  background: '#c5c8c6'
    #  foreground: '#1d1f21'

    # selection:
    #   text: CellBackground
    #   background: CellForeground

    # normal colors
    normal:
      black:   '#1c1c1c'
      red:     '#bc5653'
      green:   '#909d63'
      yellow:  '#ebc17a'
      blue:    '#7eaac7'
      magenta: '#aa6292'
      cyan:    '#86d3ce'
      white:   '#cacaca'

    # bright colors
    bright:
      black:   '#636363'
      red:     '#bc5653'
      green:   '#909d63'
      yellow:  '#ebc17a'
      blue:    '#7eaac7'
      magenta: '#aa6292'
      cyan:    '#86d3ce'
      white:   '#f7f7f7'

    # dim colors
    dim:
      black:   '#232323'
      red:     '#74423f'
      green:   '#5e6547'
      yellow:  '#8b7653'
      blue:    '#556b79'
      magenta: '#6e4962'
      cyan:    '#5c8482'
      white:   '#828282'
    foreground: '#ebdbb2'

   # Indexed Colors
    #
    # The indexed colors include all colors from 16 to 256.
    # When these are not set, they're filled with sensible defaults.
    #
    # Example:
    #   `- { index: 16, color: '#ff00ff' }`
    #
    # indexed_colors: []

    # Transparent cell backgrounds
    #
    # Whether or not `window.opacity` applies to all cell backgrounds or only to
    # the default background. When set to `true` all cells will be transparent
    # regardless of their background color.
    transparent_background_colors: true

  dracula: &dracula
    # Default colors
    primary:
      background: '#282a36'
      foreground: '#f8f8f2'

    # Normal colors
    normal:
      black:   '#000000'
      red:     '#ff5555'
      green:   '#50fa7b'
      yellow:  '#f1fa8c'
      blue:    '#caa9fa'
      magenta: '#ff79c6'
      cyan:    '#8be9fd'
      white:   '#bfbfbf'

    # Bright colors
    bright:
      black:   '#575b70'
      red:     '#ff6e67'
      green:   '#5af78e'
      yellow:  '#f4f99d'
      blue:    '#caa9fa'
      magenta: '#ff92d0'
      cyan:    '#9aedfe'
      white:   '#e6e6e6'

    transparent_background_colors: true

  onedark: &onedark
    primary:
      background: '#282c34'
      foreground: '#abb2bf'
    cursor:
      text:       CellBackground
      cursor:     '#528bff' # syntax-cursor-color
    selection:
      text:       CellForeground
      background: '#3e4451' # syntax-selection-color
    normal:
      black:      '#5c6370' # mono-3
      red:        '#e06c75' # red 1
      green:      '#98c379'
      yellow:     '#e5c07b' # orange 2
      blue:       '#61afef'
      magenta:    '#c678dd'
      cyan:       '#56b6c2'
      white:      '#828997' # mono-2

    transparent_background_colors: true

  tomorrow-night: &tomorrow-night
    # Default colors
    primary:
      background: '#1d1f21'
      foreground: '#c5c8c6'

    # Colors the cursor will use if `custom_cursor_colors` is true
    cursor:
      text: '#1d1f21'
      cursor: '#ffffff'

      # Normal colors
    normal:
      black:   '#1d1f21'
      red:     '#cc6666'
      green:   '#b5bd68'
      yellow:  '#f0c674'
      blue:    '#81a2be'
      magenta: '#b294bb'
      cyan:    '#8abeb7'
      white:   '#c5c8c6'

    # Bright colors
    bright:
      black:   '#666666'
      red:     '#d54e53'
      green:   '#b9ca4a'
      yellow:  '#e7c547'
      blue:    '#7aa6da'
      magenta: '#c397d8'
      cyan:    '#70c0b1'
      white:   '#eaeaea' 
    # Dim colors
    dim:
      black:   '#131415'
      red:     '#864343'
      green:   '#777c44'
      yellow:  '#9e824c'
      blue:    '#556a7d'
      magenta: '#75617b'
      cyan:    '#5b7d78'
      white:   '#828482'

    transparent_background_colors: true

  base16-bright-256: &base16-bright-256
      # Default colors
    primary:
      background: '0x000000'
      foreground: '0xe0e0e0'

    # Colors the cursor will use if `custom_cursor_colors` is true
    cursor:
      text: '0x000000'
      cursor: '0xe0e0e0'

    # Normal colors
    normal:
      black:   '0x000000'
      red:     '0xfb0120'
      green:   '0xa1c659'
      yellow:  '0xfda331'
      blue:    '0x6fb3d2'
      magenta: '0xd381c3'
      cyan:    '0x76c7b7'
      white:   '0xe0e0e0'

    # Bright colors
    bright:
      black:   '0xb0b0b0'
      red:     '0xfb0120'
      green:   '0xa1c659'
      yellow:  '0xfda331'
      blue:    '0x6fb3d2'
      magenta: '0xd381c3'
      cyan:    '0x76c7b7'
      white:   '0xffffff'

    indexed_colors:
      - { index: 16, color: '0xfc6d24' }
      - { index: 17, color: '0xbe643c' }
      - { index: 18, color: '0x303030' }
      - { index: 19, color: '0x505050' }
      - { index: 20, color: '0xd0d0d0' }
      - { index: 21, color: '0xf5f5f5' }

    transparent_background_colors: true
  
  base16-default-dark-256: &base16-default-dark-256
  # Default colors
    primary:
      background: '0x181818'
      foreground: '0xd8d8d8'

    # Colors the cursor will use if `custom_cursor_colors` is true
    cursor:
      text: '0x181818'
      cursor: '0xd8d8d8'

    # Normal colors
    normal:
      black:   '0x181818'
      red:     '0xab4642'
      green:   '0xa1b56c'
      yellow:  '0xf7ca88'
      blue:    '0x7cafc2'
      magenta: '0xba8baf'
      cyan:    '0x86c1b9'
      white:   '0xd8d8d8'

    # Bright colors
    bright:
      black:   '0x585858'
      red:     '0xab4642'
      green:   '0xa1b56c'
      yellow:  '0xf7ca88'
      blue:    '0x7cafc2'
      magenta: '0xba8baf'
      cyan:    '0x86c1b9'
      white:   '0xf8f8f8'

    indexed_colors:
      - { index: 16, color: '0xdc9656' }
      - { index: 17, color: '0xa16946' }
      - { index: 18, color: '0x282828' }
      - { index: 19, color: '0x383838' }
      - { index: 20, color: '0xb8b8b8' }
      - { index: 21, color: '0xe8e8e8' }

    transparent_background_colors: true

  base16-dracula-256: &base16-dracula-256
    # Default colors
    primary:
      background: '0x282936'
      foreground: '0xe9e9f4'

    # Colors the cursor will use if `custom_cursor_colors` is true
    cursor:
      text: '0x282936'
      cursor: '0xe9e9f4'

    # Normal colors
    normal:
      black:   '0x282936'
      red:     '0xea51b2'
      green:   '0xebff87'
      yellow:  '0x00f769'
      blue:    '0x62d6e8'
      magenta: '0xb45bcf'
      cyan:    '0xa1efe4'
      white:   '0xe9e9f4'

    # Bright colors
    bright:
      black:   '0x626483'
      red:     '0xea51b2'
      green:   '0xebff87'
      yellow:  '0x00f769'
      blue:    '0x62d6e8'
      magenta: '0xb45bcf'
      cyan:    '0xa1efe4'
      white:   '0xf7f7fb'

    indexed_colors:
      - { index: 16, color: '0xb45bcf' }
      - { index: 17, color: '0x00f769' }
      - { index: 18, color: '0x3a3c4e' }
      - { index: 19, color: '0x4d4f68' }
      - { index: 20, color: '0x62d6e8' }
      - { index: 21, color: '0xf1f2f8' }

    transparent_background_colors: true

  base16-gruvbox-dark-hard-256: &base16-gruvbox-dark-hard-256
    primary:
      background: '0x1d2021'
      foreground: '0xd5c4a1'

    # Colors the cursor will use if `custom_cursor_colors` is true
    cursor:
      text: '0x1d2021'
      cursor: '0xd5c4a1'

    # Normal colors
    normal:
      black:   '0x1d2021'
      red:     '0xfb4934'
      green:   '0xb8bb26'
      yellow:  '0xfabd2f'
      blue:    '0x83a598'
      magenta: '0xd3869b'
      cyan:    '0x8ec07c'
      white:   '0xd5c4a1'

    # Bright colors
    bright:
      black:   '0x665c54'
      red:     '0xfb4934'
      green:   '0xb8bb26'
      yellow:  '0xfabd2f'
      blue:    '0x83a598'
      magenta: '0xd3869b'
      cyan:    '0x8ec07c'
      white:   '0xfbf1c7'

    indexed_colors:
      - { index: 16, color: '0xfe8019' }
      - { index: 17, color: '0xd65d0e' }
      - { index: 18, color: '0x3c3836' }
      - { index: 19, color: '0x504945' }
      - { index: 20, color: '0xbdae93' }
      - { index: 21, color: '0xebdbb2' }

    transparent_background_colors: true
  base16-material-256: &base16-material-256
    # Default colors
    primary:
      background: '0x263238'
      foreground: '0xeeffff'

    # Colors the cursor will use if `custom_cursor_colors` is true
    cursor:
      text: '0x263238'
      cursor: '0xeeffff'

    # Normal colors
    normal:
      black:   '0x263238'
      red:     '0xf07178'
      green:   '0xc3e88d'
      yellow:  '0xffcb6b'
      blue:    '0x82aaff'
      magenta: '0xc792ea'
      cyan:    '0x89ddff'
      white:   '0xeeffff'

    # Bright colors
    bright:
      black:   '0x546e7a'
      red:     '0xf07178'
      green:   '0xc3e88d'
      yellow:  '0xffcb6b'
      blue:    '0x82aaff'
      magenta: '0xc792ea'
      cyan:    '0x89ddff'
      white:   '0xffffff'

    indexed_colors:
      - { index: 16, color: '0xf78c6c' }
      - { index: 17, color: '0xff5370' }
      - { index: 18, color: '0x2e3c43' }
      - { index: 19, color: '0x314549' }
      - { index: 20, color: '0xb2ccd6' }
      - { index: 21, color: '0xeeffff' } 

    transparent_background_colors: true

  base16-onedark-256: &base16-onedark-256
  # Default colors
    primary:
      background: '0x282c34'
      foreground: '0xabb2bf'

    # Colors the cursor will use if `custom_cursor_colors` is true
    cursor:
      text: '0x282c34'
      cursor: '0xabb2bf'

    # Normal colors
    normal:
      black:   '0x282c34'
      red:     '0xe06c75'
      green:   '0x98c379'
      yellow:  '0xe5c07b'
      blue:    '0x61afef'
      magenta: '0xc678dd'
      cyan:    '0x56b6c2'
      white:   '0xabb2bf'

    # Bright colors
    bright:
      black:   '0x545862'
      red:     '0xe06c75'
      green:   '0x98c379'
      yellow:  '0xe5c07b'
      blue:    '0x61afef'
      magenta: '0xc678dd'
      cyan:    '0x56b6c2'
      white:   '0xc8ccd4'

    indexed_colors:
      - { index: 16, color: '0xd19a66' }
      - { index: 17, color: '0xbe5046' }
      - { index: 18, color: '0x353b45' }
      - { index: 19, color: '0x3e4451' }
      - { index: 20, color: '0x565c64' }
      - { index: 21, color: '0xb6bdca' }

    transparent_background_colors: true
  

  base16-rebecca-256: &base16-rebecca-256
    # Default colors
    primary:
      background: '0x292a44'
      foreground: '0xf1eff8'

    # Colors the cursor will use if `custom_cursor_colors` is true
    cursor:
      text: '0x292a44'
      cursor: '0xf1eff8'

    # Normal colors
    normal:
      black:   '0x292a44'
      red:     '0xa0a0c5'
      green:   '0x6dfedf'
      yellow:  '0xae81ff'
      blue:    '0x2de0a7'
      magenta: '0x7aa5ff'
      cyan:    '0x8eaee0'
      white:   '0xf1eff8'

    # Bright colors
    bright:
      black:   '0x666699'
      red:     '0xa0a0c5'
      green:   '0x6dfedf'
      yellow:  '0xae81ff'
      blue:    '0x2de0a7'
      magenta: '0x7aa5ff'
      cyan:    '0x8eaee0'
      white:   '0x53495d'

    indexed_colors:
      - { index: 16, color: '0xefe4a1' }
      - { index: 17, color: '0xff79c6' }
      - { index: 18, color: '0x663399' }
      - { index: 19, color: '0x383a62' }
      - { index: 20, color: '0xa0a0c5' }
      - { index: 21, color: '0xccccff' }

    transparent_background_colors: true

  base16-tomorrow-night-eighties-256: &base16-tomorrow-night-eighties-256
    # Default colors
    primary:
      background: '0x2d2d2d'
      foreground: '0xcccccc'

    # Colors the cursor will use if `custom_cursor_colors` is true
    cursor:
      text: '0x2d2d2d'
      cursor: '0xcccccc'

    # Normal colors
    normal:
      black:   '0x2d2d2d'
      red:     '0xf2777a'
      green:   '0x99cc99'
      yellow:  '0xffcc66'
      blue:    '0x6699cc'
      magenta: '0xcc99cc'
      cyan:    '0x66cccc'
      white:   '0xcccccc'

    # Bright colors
    bright:
      black:   '0x999999'
      red:     '0xf2777a'
      green:   '0x99cc99'
      yellow:  '0xffcc66'
      blue:    '0x6699cc'
      magenta: '0xcc99cc'
      cyan:    '0x66cccc'
      white:   '0xffffff'

    indexed_colors:
      - { index: 16, color: '0xf99157' }
      - { index: 17, color: '0xa3685a' }
      - { index: 18, color: '0x393939' }
      - { index: 19, color: '0x515151' }
      - { index: 20, color: '0xb4b7b4' }
      - { index: 21, color: '0xe0e0e0' }

    transparent_background_colors: true

  hepburn: &hepburn
    cursor:
      text: CellBackground
      cursor: CellForeground
# Hepburn
    primary:
      background: '0x000000'
      foreground: '0xfbf1c7'
    normal:
      black:   '0x282828'
      red:     '0xcc241d'
      green:   '0x98971a'
      yellow:  '0xd79921'
      blue:    '0x458588'
      magenta: '0xb16286'
      cyan:    '0x689d6a'
      white:   '0xa89984'
    bright:
      black:   '0x928374'
      red:     '0xfb4934'
      green:   '0xb8bb26'
      yellow:  '0xfabd2f'
      blue:    '0x83a598'
      magenta: '0xd3869b'
      cyan:    '0x8ec07c'
      white:   '0xebdbb2'

    indexed_colors:
      - { index: 16, color: '0xdc9656' }
      - { index: 17, color: '0xa16946' }
      - { index: 18, color: '0x282828' }
      - { index: 19, color: '0x383838' }
      - { index: 20, color: '0xb8b8b8' }
      - { index: 21, color: '0xe8e8e8' }

    selection:
      text: '0xffffff'
      background: '0xdc3232'
      white:   '0xffffff'

    transparent_background_colors: true

# - afterglow
# - dracula
# - onedark
# - tomorrow-night
# - base16-bright-256
# - base16-default-dark-256
# - base16-dracula-256
# - base16-gruvbox-dark-hard-256
# - base16-material-256
# - base16-onedark-256
# - base16-rebecca-256
# - base16-tomorrow-night-eighties-256
# - hepburn
colors: *base16-onedark-256
