#!/bin/sh

sxhkd &
picom &
nitrogen --restore &
/usr/bin/xsettingsd &
# [ -x ~/.config/polybar/launch.sh ] && ~/.config/polybar/launch.sh &
# $HOME/.config/polybar/docky/scripts/pywal.sh $HOME/Pictures/wallpaper &
# $HOME/.config/polybar/launch.sh --docky &
$HOME/.config/polybar/launch.sh --cust &
# pcmanfm --desktop & # display desktop dirs & files
docker-compose -f $HOME/.config/clash/docker-compose.yaml up -d &
fcitx5 &
# [ -x ~/.cargo-target/release/buzz ] && ~/.cargo-target/release/buzz &
# if [ -x ~/.cargo-target/release/keybase-chat-notifier ]; then
	# keybase chat api-listen | ~/.cargo-target/release/keybase-chat-notifier &
# fi
# psensor &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         0
bspc config window_gap           1
bspc config focused_border_color \#3c3836
bspc config normal_border_color  \#1d2021

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc rule -a firefoxdeveloperedition desktop='^1' state=tiled
bspc rule -a google-chrome-stable desktop='^1' state=tiled

# https://github.com/baskerville/bspwm/issues/291
# only works due to https://github.com/dasJ/spotifywm
# bspc rule -a Spotify desktop='^6' state=pseudo_tiled
bspc rule -a dingtalk desktop='^5'
# bspc rule -a wps desktop='^4'
bspc rule -a code desktop='^3'
bspc rule -a netease-cloud-music desktop='^6' state=pseudo_tiled
bspc rule -a virtualbox desktop='^4'
bspc rule -a anaconda-navigator desktop='^3'
# bspc rule -a ulauncher focus=on
# bspc rule -a sxiv state=floating center=true
bspc rule -a polybar border=off manage=off

bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true
